# Generated by Django 4.1 on 2023-08-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('startDate', models.DateField(blank=True)),
                ('catalogID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementCode', models.CharField(max_length=100)),
                ('elementValue', models.CharField(max_length=300)),
                ('catalogVersionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.catalogversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='catalogversion',
            constraint=models.UniqueConstraint(fields=('catalogID', 'version'), name='unique_catalogID_version'),
        ),
        migrations.AddConstraint(
            model_name='catalogversion',
            constraint=models.UniqueConstraint(fields=('catalogID', 'startDate'), name='unique_catalogID_startDate'),
        ),
        migrations.AddConstraint(
            model_name='catalogelement',
            constraint=models.UniqueConstraint(fields=('catalogVersionID', 'elementCode'), name='unique_catalogVersionID_elementCode'),
        ),
    ]
